pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=master
      - author=dependabot-preview[bot]
      - 'status-success=ci/circleci: test'
      - 'status-success=ci/circleci: image'
      - 'status-success=ci/circleci: integration_test'
      - 'status-success=ci/circleci: api_test'
    actions:
      merge:
        method: merge
        strict: true
        strict_method: squash
      delete_head_branch:
