version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.12.0
    steps:
      - checkout

      - restore_cache:
          key: node-modules-{{ checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}

      - run:
          name: Print versions
          command: node --version && yarn --version

      - run:
          name: Install node packages
          command: yarn install

      - save_cache:
          key: node-modules-{{ checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Install flow typed
          command: yarn flowtyped

      - run:
          name: Run tests
          command: yarn test:unit

      - run:
          name: Run eslint
          command: yarn test:lint

      - run:
          name: Run flow
          command: yarn test:flow

  image:
      docker:
        - image: circleci/node:12.12.0

      steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - checkout

      - run:
          name: Docker login
          command: docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}

      - run:
          name: Build image
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} .

      - run:
          name: Push image
          command: docker push ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}

      - run:
          name: Push latest image
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              docker tag ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} ${CIRCLE_PROJECT_REPONAME}:latest
              docker push ${CIRCLE_PROJECT_REPONAME}:push
            fi

workflows:
  version: 2
  build:
    jobs:
      - test
      - image:
          requires:
            - test
