version: 2.1

jobs:
  test:
    docker:
      - image: node:12.11.1
    steps:
      - checkout

      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}

      - run:
          name: Print versions
          command: node --version && yarn --version

      - run:
          name: Install node packages
          command: yarn install

      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Install flow typed
          command: yarn flowtyped

      - run:
          name: Run eslint
          command: yarn test:lint

      - run:
          name: Run flow
          command: yarn test:flow

      - run:
          name: Run tests
          command: NODE_ENV=development yarn test:unit

  image:
      docker:
        - image: docker:latest

      steps:
        - setup_remote_docker:
            version: 18.09.3

        - checkout

        - run:
            name: Setup environment
            command: |
              if [ "$CIRCLE_BRANCH" = "master" ]; then
                echo "export IMAGE_TAG='latest'" >> $BASH_ENV
              else
                echo "export IMAGE_TAG='$(echo "${CIRCLECI_BRANCH}" | sed 'sx/x-xg')'" >> $BASH_ENV
              fi
        - run: export

        - run:
            name: Docker login
            command: docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}

        - run:
            name: Build image
            command: docker build -t kodiconnect/kodi-connect:${IMAGE_TAG} .

        - run:
            name: Push image
            command: docker push kodiconnect/kodi-connect:${IMAGE_TAG}

workflows:
  version: 2
  build:
    jobs:
      - test
      - image:
          requires:
            - test
          filters:
            branches:
              ignore:
                - /^dependabot\/.*/

