version: '2.4'
services:
  app:
    environment:
      HISTFILE: '/root/.bashhistory/.bash_history'
    volumes:
      - vscode-server-extensions:/root/.vscode-server/extensions
      - bash-history:/root/.bashhistory
      - $HOME/.ssh:/root/.ssh
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
volumes:
  vscode-server-extensions:
  bash-history:
